/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.RoleAdministrator;

import work.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;
/**
 *
 * @author naiyaadatiya
 */
public class AdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminWorkAreaPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    public AdminWorkAreaPanel(JPanel userProcessContainer, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        valuelabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enterpriselabel = new javax.swing.JLabel();
        manageorganizationbutton = new javax.swing.JButton();
        manageuserbutton = new javax.swing.JButton();
        managestaffbutton = new javax.swing.JButton();
        valuelabel = new javax.swing.JLabel();

        jLabel1.setText("Administrative Role");

        enterpriselabel.setText("Enterprise");

        manageorganizationbutton.setText("Manage Organization");
        manageorganizationbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageorganizationbuttonActionPerformed(evt);
            }
        });

        manageuserbutton.setText("Manage User");
        manageuserbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuserbuttonActionPerformed(evt);
            }
        });

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriselabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton manageorganizationbutton;
    private javax.swing.JButton managestaffbutton;
    private javax.swing.JButton manageuserbutton;
    private javax.swing.JLabel valuelabel;
    // End of variables declaration//GEN-END:variables
}
