/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.RoleYogaInstructor;

/**
 *
 * @author keerthanapanyam
 */
import work.EcoSystem;
import work.Enterprise.Enterprise;
import work.Enterprise.PhysicalWellbeingEnterprise;
import work.Network.Network;
import work.Organization.Organization;
import work.Organization.YogaOrganization;
import work.UserAcc.UserAcc;
import work.FlowQueue.YogaInstructorFlowReq;
import userInterface.Client.ClientLoginWorkAreaPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;






public class RequestYogaInstructorPanel extends javax.swing.JPanel {

    /**
     * Creates new form RoleYogaInstructor
     */
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAcc userAcc;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;
//    private JTextField Messagetxt;
//    private JLabel Messagelbl;
//    private JButton RequestYogaInstructorbtn;
//    private JButton Backbtn;
//    private JLabel Enterpriselbl;
//    private JLabel Valuelbl;
    
    
    
    
    
    
    
    public RequestYogaInstructorPanel(JPanel userProcessContainer, UserAcc account, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network targetNetwork) {
        initComponents();
        
       this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAcc = account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        this.targetNetwork = targetNetwork;
        if(null != enterprise) {
        Valuelbl.setText(enterprise.getName()); 
        
        
    }
        
    }

    public RequestYogaInstructorPanel(JFrame userProcessContainer, UserAcc userAcc, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network network) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Backbtn = new javax.swing.JButton();
        Enterpriselbl = new javax.swing.JLabel();
        Valuelbl = new javax.swing.JLabel();
        Messagelbl = new javax.swing.JLabel();
        Messagetxt = new javax.swing.JTextField();
        RequestYogaInstructorbtn = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Backbtn.setText("Back");
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        Enterpriselbl.setText("Enterprise:");
        add(Enterpriselbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 496, -1, -1));
        add(Valuelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 496, -1, -1));

        Messagelbl.setText("Add message text:");
        add(Messagelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 528, -1, -1));

        Messagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessagetxtActionPerformed(evt);
            }
        });
        add(Messagetxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 525, 125, -1));

        RequestYogaInstructorbtn.setText("Book Appointment");
        add(RequestYogaInstructorbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 626, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void MessagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessagetxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel Enterpriselbl;
    private javax.swing.JLabel Messagelbl;
    private javax.swing.JTextField Messagetxt;
    private javax.swing.JButton RequestYogaInstructorbtn;
    private javax.swing.JLabel Valuelbl;
    // End of variables declaration//GEN-END:variables
}
