/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.RoleMeditationInstructor;

import work.EcoSystem;
import work.Enterprise.Enterprise;
import work.Network.Network;
import work.Organization.MedicareOrganization;
import work.Organization.MeditationOrganization;
import work.Organization.Organization;
import work.UserAcc.UserAcc;
import work.FlowQueue.MeditationInstructorFlowReq;
import work.FlowQueue.FlowReq;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author keerthanapanyam
 */
public class WorkAreaMeditationInstructorPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkAreaMeditationInstructorPanel1
     */
    private JPanel userProcessContainer;
    private MeditationOrganization housecleanorganization;
    private Enterprise enterprise;
    private UserAcc userAcc;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork; 
    
    
    public WorkAreaMeditationInstructorPanel(JPanel userProcessContainer, UserAcc account, Organization organization, Enterprise enterprise, EcoSystem system, Network sourceNetwork) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.housecleanorganization = (MeditationOrganization) organization;
        this.enterprise = enterprise;
        this.userAcc = account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        Valuelbl.setText(organization.getName());
        populateRequestTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        FlowReqtbl = new javax.swing.JTable();
        Assignbtn = new javax.swing.JButton();
        Processbtn = new javax.swing.JButton();
        Declinebtn = new javax.swing.JButton();
        Organizationlbl = new javax.swing.JLabel();
        Valuelbl = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlowReqtbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Message", "Sender", "Reciever", "Status"
            }
        ));
        FlowReqtbl.setToolTipText("");
        jScrollPane2.setViewportView(FlowReqtbl);

        Assignbtn.setBackground(new java.awt.Color(178, 189, 155));
        Assignbtn.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        Assignbtn.setText("Assign");
        Assignbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AssignbtnActionPerformed(evt);
            }
        });

        Processbtn.setBackground(new java.awt.Color(178, 189, 155));
        Processbtn.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Processbtn.setText("Process");
        Processbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcessbtnActionPerformed(evt);
            }
        });

        Declinebtn.setBackground(new java.awt.Color(178, 189, 155));
        Declinebtn.setFont(new java.awt.Font("Avenir", 0, 18)); // NOI18N
        Declinebtn.setText("Decline");
        Declinebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeclinebtnActionPerformed(evt);
            }
        });

        Organizationlbl.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        Organizationlbl.setText("ORGANIZATION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(85, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 537, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Assignbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Processbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                    .addComponent(Declinebtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(Organizationlbl)
                .addGap(33, 33, 33)
                .addComponent(Valuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Organizationlbl)
                    .addComponent(Valuelbl, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Assignbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Processbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Declinebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ProcessbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcessbtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = FlowReqtbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        FlowReq request = (FlowReq)FlowReqtbl.getValueAt(selectedRow,0);
        request.setReceiver(userAcc);
        request.setStatus("Processed");
        populateRequestTable();
    }//GEN-LAST:event_ProcessbtnActionPerformed

    private void DeclinebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeclinebtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = FlowReqtbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        FlowReq request = (FlowReq)FlowReqtbl.getValueAt(selectedRow, 0);
        request.setReceiver(userAcc);
        request.setStatus("Declined");

        populateRequestTable();
    }//GEN-LAST:event_DeclinebtnActionPerformed

    private void AssignbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AssignbtnActionPerformed
        // TODO add your handling code here:
         int selectedRow = FlowReqtbl.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(this, "Please select at least one row");
            return;
        }

        FlowReq request = (FlowReq)FlowReqtbl.getValueAt(selectedRow, 0);
        request.setReceiver(userAcc);
        request.setStatus("Confirmed");

        populateRequestTable();
    }//GEN-LAST:event_AssignbtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Assignbtn;
    private javax.swing.JButton Declinebtn;
    private javax.swing.JTable FlowReqtbl;
    private javax.swing.JLabel Organizationlbl;
    private javax.swing.JButton Processbtn;
    private javax.swing.JLabel Valuelbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
