/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.SysAdminWorkArea;

import work.EcoSystem;
import work.Enterprise.Enterprise;
import work.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JComboBox;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keerthanapanyam
 */
public class ManageEnterprisePanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEnterprisePanel
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    
    
    public ManageEnterprisePanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateTable();
        populateComboBox();
    }
         private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) Enterprisetbl.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                Object[] row = new Object[3];
                row[0] = enterprise.getName();
                row[1] = network.getName();
                row[2] = enterprise.getEnterpriseType().getValue();

                model.addRow(row);
            }
        }
    }

    private void populateComboBox() {
        Networkcb.removeAllItems();
        EnterpriseTypecb.removeAllItems();

        for (Network network : system.getNetworkList()) {
            Networkcb.addItem(network);
        }

        for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            EnterpriseTypecb.addItem(type);
        }

    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Networkcb = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        EnterpriseTypecb = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        Nametxt = new javax.swing.JTextField();
        Submitbtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Enterprisetbl = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel1.setText("Network:");
        add(jLabel1);
        jLabel1.setBounds(146, 103, 52, 18);

        Networkcb.setBackground(new java.awt.Color(220, 227, 204));
        Networkcb.setEditable(true);
        Networkcb.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Networkcb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Networkcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetworkcbActionPerformed(evt);
            }
        });
        add(Networkcb);
        Networkcb.setBounds(216, 100, 119, 24);

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel2.setText("Enterprise Type:");
        add(jLabel2);
        jLabel2.setBounds(104, 133, 94, 18);

        EnterpriseTypecb.setBackground(new java.awt.Color(220, 227, 204));
        EnterpriseTypecb.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        EnterpriseTypecb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(EnterpriseTypecb);
        EnterpriseTypecb.setBounds(216, 130, 119, 24);

        jLabel3.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel3.setText("Name:");
        add(jLabel3);
        jLabel3.setBounds(159, 160, 39, 18);

        Nametxt.setBackground(new java.awt.Color(220, 227, 204));
        Nametxt.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        add(Nametxt);
        Nametxt.setBounds(216, 160, 119, 24);

        Submitbtn.setBackground(new java.awt.Color(178, 189, 155));
        Submitbtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Submitbtn.setText("Submit");
        Submitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitbtnActionPerformed(evt);
            }
        });
        add(Submitbtn);
        Submitbtn.setBounds(302, 235, 72, 24);

        Enterprisetbl.setBackground(new java.awt.Color(220, 227, 204));
        Enterprisetbl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Enterprisetbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Enterprise Name", "Network", "Type"
            }
        ));
        jScrollPane1.setViewportView(Enterprisetbl);

        add(jScrollPane1);
        jScrollPane1.setBounds(422, 100, 485, 99);

        jButton2.setBackground(new java.awt.Color(178, 189, 155));
        jButton2.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(32, 25, 72, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void NetworkcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetworkcbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetworkcbActionPerformed

    private void SubmitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitbtnActionPerformed
        // TODO add your handling code here:
         Network network = (Network) Networkcb.getSelectedItem();
        Enterprise.EnterpriseType type = (Enterprise.EnterpriseType) EnterpriseTypecb.getSelectedItem();

        if (network == null || type == null) {
            JOptionPane.showMessageDialog(null, "Invalid Input!");
            return;
        }

        String name = Nametxt.getText();
        if (!name.isEmpty()) {
            if (network.checkifEnterpriseIsUnique(name)) {
                Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, type);
                populateTable();
            } else {
                JOptionPane.showMessageDialog(this, "Enterprise name already exists");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Check your input");
        }

        Nametxt.setText("");
    }//GEN-LAST:event_SubmitbtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaPanel sysAdminwjp = (SysAdminWorkAreaPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox EnterpriseTypecb;
    private javax.swing.JTable Enterprisetbl;
    private javax.swing.JTextField Nametxt;
    private javax.swing.JComboBox Networkcb;
    private javax.swing.JButton Submitbtn;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
