/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.SysAdminWorkArea;

import work.EcoSystem;
import work.Network.Network;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author keerthanapanyam
 */
public class ManageNetworkPanel extends javax.swing.JPanel {

    
    private JPanel userProcessContainer;
    private EcoSystem system; 
    
    public ManageNetworkPanel(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.system = system;

        populateNetworkTable();
    }
    private void populateNetworkTable() {
        DefaultTableModel model = (DefaultTableModel) Networktbl.getModel();

        model.setRowCount(0);
        for (Network network : system.getNetworkList()) {
            Object[] row = new Object[1];
            row[0] = network.getName();
      
          model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        Networktbl = new javax.swing.JTable();
        Backbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        NetworkNametxt = new javax.swing.JTextField();
        Addbtn = new javax.swing.JButton();

        setLayout(null);

        jScrollPane3.setBackground(new java.awt.Color(220, 227, 204));

        Networktbl.setBackground(new java.awt.Color(220, 227, 204));
        Networktbl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Networktbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Name"
            }
        ));
        Networktbl.setToolTipText("");
        jScrollPane3.setViewportView(Networktbl);

        add(jScrollPane3);
        jScrollPane3.setBounds(464, 102, 266, 147);

        Backbtn.setBackground(new java.awt.Color(178, 189, 155));
        Backbtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn);
        Backbtn.setBounds(28, 24, 72, 24);

        jLabel1.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel1.setText("Network Name:");
        add(jLabel1);
        jLabel1.setBounds(41, 220, 91, 18);

        NetworkNametxt.setBackground(new java.awt.Color(220, 227, 204));
        NetworkNametxt.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        NetworkNametxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NetworkNametxtActionPerformed(evt);
            }
        });
        add(NetworkNametxt);
        NetworkNametxt.setBounds(138, 217, 81, 24);

        Addbtn.setBackground(new java.awt.Color(178, 189, 155));
        Addbtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Addbtn.setText("Add");
        Addbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddbtnActionPerformed(evt);
            }
        });
        add(Addbtn);
        Addbtn.setBounds(77, 280, 72, 24);
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SysAdminWorkAreaPanel sysAdminwjp = (SysAdminWorkAreaPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed

    private void NetworkNametxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NetworkNametxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NetworkNametxtActionPerformed

    private void AddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddbtnActionPerformed
        // TODO add your handling code here:
        
         String name = NetworkNametxt.getText();
        if (!name.isEmpty() && name.length()>2) {
            if (system.checkifNetworkIsUnique(name)) {
                Network network = system.createAndAddNetwork();
                network.setName(name);
                populateNetworkTable();
            } else {
                JOptionPane.showMessageDialog(this, "Network already exists");
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please check your network input");
        }
        NetworkNametxt.setText("");
    }//GEN-LAST:event_AddbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Addbtn;
    private javax.swing.JButton Backbtn;
    private javax.swing.JTextField NetworkNametxt;
    private javax.swing.JTable Networktbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
