/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.SysAdminWorkArea;


import java.awt.CardLayout;
import javax.swing.JPanel;
import work.EcoSystem;
/**
 *
 * @author keerthanapanyam
 */
public class SysAdminWorkAreaPanel extends javax.swing.JPanel {

    /**
     * Creates new form SysAdminWorkArea
     */
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    
    public SysAdminWorkAreaPanel(JPanel userProcessContainer,EcoSystem ecosystem) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.ecosystem=ecosystem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ManageNetworkbtn = new javax.swing.JButton();
        ManageEnterprisebtn = new javax.swing.JButton();
        ManageEnterpriseAdmin = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        ManageNetworkbtn.setBackground(new java.awt.Color(178, 189, 155));
        ManageNetworkbtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        ManageNetworkbtn.setText("Manage Network");
        ManageNetworkbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageNetworkbtnActionPerformed(evt);
            }
        });

        ManageEnterprisebtn.setBackground(new java.awt.Color(178, 189, 155));
        ManageEnterprisebtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        ManageEnterprisebtn.setText("Manage Enteprise");
        ManageEnterprisebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterprisebtnActionPerformed(evt);
            }
        });

        ManageEnterpriseAdmin.setBackground(new java.awt.Color(178, 189, 155));
        ManageEnterpriseAdmin.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        ManageEnterpriseAdmin.setText("Manage Enterprise Admin");
        ManageEnterpriseAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageEnterpriseAdminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(ManageNetworkbtn)
                        .addGap(99, 99, 99)
                        .addComponent(ManageEnterprisebtn))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(ManageEnterpriseAdmin)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(172, 172, 172)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ManageNetworkbtn)
                    .addComponent(ManageEnterprisebtn))
                .addGap(59, 59, 59)
                .addComponent(ManageEnterpriseAdmin)
                .addContainerGap(335, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        add(jSplitPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ManageNetworkbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageNetworkbtnActionPerformed
        // TODO add your handling code here:
        ManageNetworkPanel manageNetworkJPanel=new ManageNetworkPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageNetworkJPanel",manageNetworkJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageNetworkbtnActionPerformed

    private void ManageEnterprisebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterprisebtnActionPerformed
        // TODO add your handling code here:
        ManageEnterprisePanel manageEnterpriseJPanel=new ManageEnterprisePanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseJPanel",manageEnterpriseJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterprisebtnActionPerformed

    private void ManageEnterpriseAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageEnterpriseAdminActionPerformed
        // TODO add your handling code here:
        ManageEnterpriseAdminPanel manageEnterpriseAdminJPanel=new ManageEnterpriseAdminPanel(userProcessContainer, ecosystem);
        userProcessContainer.add("manageEnterpriseAdminJPanel",manageEnterpriseAdminJPanel);
        CardLayout layout=(CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ManageEnterpriseAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageEnterpriseAdmin;
    private javax.swing.JButton ManageEnterprisebtn;
    private javax.swing.JButton ManageNetworkbtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSplitPane jSplitPane1;
    // End of variables declaration//GEN-END:variables
}
