/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.Client;

import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author naiyaadatiya
 */
public class otpPanel extends javax.swing.JPanel {

    /**
     * Creates new form otpPanel
     */
    JPanel userProcessContainer;
    String otp;
    
    public otpPanel(JPanel userProcessContainer, String otp) {
        initComponents();
        
        this.userProcessContainer = userProcessContainer;
        this.otp = otp;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        otptextfield = new javax.swing.JTextField();
        submitbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        jLabel2.setText("OTP");
        add(jLabel2);
        jLabel2.setBounds(271, 158, 25, 18);

        otptextfield.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        add(otptextfield);
        otptextfield.setBounds(314, 155, 117, 24);

        submitbutton.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        submitbutton.setText("VALIDATE OTP");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        add(submitbutton);
        submitbutton.setBounds(271, 214, 136, 24);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/userInterface/Client/950x350-pastel-blue-solid-color-background.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        add(jLabel1);
        jLabel1.setBounds(0, -80, 760, 510);
    }// </editor-fold>//GEN-END:initComponents

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed
        // TODO add your handling code here:
                if(validateOtp(otp)) {
            JOptionPane.showMessageDialog(this, "Correct OTP");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            WorkAreaClientPanel dwjp = (WorkAreaClientPanel) component;
            dwjp.validateOtp(true);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        } else {
            JOptionPane.showMessageDialog(this, "Incorrect OTP");
            userProcessContainer.remove(this);
            Component[] componentArray = userProcessContainer.getComponents();
            Component component = componentArray[componentArray.length - 1];
            WorkAreaClientPanel dwjp = (WorkAreaClientPanel) component;
            dwjp.validateOtp(false);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.previous(userProcessContainer);
        }
    
    }//GEN-LAST:event_submitbuttonActionPerformed
 private boolean validateOtp(String otp) {
        if(otptextfield.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Otp cannot be empty");
        }
        if(otptextfield.getText().equals(otp)) {
            return true;
        } else {
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField otptextfield;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
