/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package userInterface.RoleSpa;

import work.EcoSystem;
import work.Enterprise.Enterprise;
import work.Enterprise.SelfCareEnterprise;
import work.Network.Network;
import work.Organization.Organization;
import work.Organization.SpaOrganization;
import work.UserAcc.UserAcc;
import work.FlowQueue.SpaFlowReq;
import userInterface.Client.ClientLoginWorkAreaPanel;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author keerthanapanyam
 */
public class RequestSpaPanel extends javax.swing.JPanel {

    /**
     * Creates new form RequestSpaPanel
     */
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private UserAcc userAcc;
    private EcoSystem system;
    private Network sourceNetwork;
    private Network targetNetwork;
    
    
    
    public RequestSpaPanel(JPanel userProcessContainer, UserAcc account, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network targetNetwork) {
    initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAcc= account;
        this.system = system;
        this.sourceNetwork = sourceNetwork;
        this.targetNetwork = targetNetwork;
        if(null != enterprise) {
            Valuelbl.setText(enterprise.getName());
        }
        
    }

    public RequestSpaPanel(JFrame userProcessContainer, UserAcc userAcc, Enterprise enterprise, EcoSystem system, Network sourceNetwork, Network network) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    public RequestSpaPanel(JPanel userProcessContainer, Object object, EcoSystem system, Object object0) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Messagelbl = new javax.swing.JLabel();
        Messagetxt = new javax.swing.JTextField();
        RequestSpabtn = new javax.swing.JButton();
        Valuelbl = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();
        Enterpriselbl = new javax.swing.JLabel();

        Messagelbl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Messagelbl.setText("Add message text:");

        Messagetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MessagetxtActionPerformed(evt);
            }
        });

        RequestSpabtn.setBackground(new java.awt.Color(178, 189, 155));
        RequestSpabtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        RequestSpabtn.setText("Book Appointment");
        RequestSpabtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RequestSpabtnActionPerformed(evt);
            }
        });

        Valuelbl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Valuelbl.setText("-");

        Backbtn.setBackground(new java.awt.Color(178, 189, 155));
        Backbtn.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Backbtn.setText("Back");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });

        Enterpriselbl.setFont(new java.awt.Font("Avenir", 0, 13)); // NOI18N
        Enterpriselbl.setText("Enterprise:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Backbtn)
                        .addGap(500, 500, 500))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Enterpriselbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Valuelbl))
                            .addComponent(Messagelbl))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Messagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(RequestSpabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Backbtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Valuelbl)
                    .addComponent(Enterpriselbl))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Messagelbl)
                    .addComponent(Messagetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(RequestSpabtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MessagetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MessagetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MessagetxtActionPerformed

    private void RequestSpabtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RequestSpabtnActionPerformed
        // TODO add your handling code here:
        String message = Messagetxt.getText();
        if (!message.isEmpty()) {
            SpaFlowReq request = new SpaFlowReq();
            request.setMessage(message);
            request.setSender(userAcc);
            request.setStatus("Sent");

            Organization org = null;
            Enterprise ent = null;
            if (sourceNetwork != targetNetwork) {
                for (Enterprise enterprise : targetNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof SelfCareEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof SpaOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            } else {
                for (Enterprise enterprise : sourceNetwork.getEnterpriseDirectory().getEnterpriseList()) {
                    if (enterprise instanceof SelfCareEnterprise) {
                        ent = enterprise;
                    }
                    for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()) {
                        if (organization instanceof SpaOrganization) {
                            org = organization;
                            break;
                        }
                    }
                }
            }
            if (org != null) {
                org.getWorkQueue().getflowReqList().add(request);
                userAcc.getFlowQueue().getflowReqList().add(request);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please enter correct input");
        }
        Messagetxt.setText("");
        
    }//GEN-LAST:event_RequestSpabtnActionPerformed

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ClientLoginWorkAreaPanel clwjp = (ClientLoginWorkAreaPanel) component;
        clwjp.populateRequestTable(sourceNetwork);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_BackbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JLabel Enterpriselbl;
    private javax.swing.JLabel Messagelbl;
    private javax.swing.JTextField Messagetxt;
    private javax.swing.JButton RequestSpabtn;
    private javax.swing.JLabel Valuelbl;
    // End of variables declaration//GEN-END:variables
}
